### ISSUE TITLE
Polish Tree Bug

### ISSUE THREAD

**Issue by 22oroda** [malashin/hoi4treesnap#5] opened 2022-07-26 21:28 UTC
Trying to get a picture of the polish focus tree for vanilla Hoi4, but everytime I click generate image it returns this error:

[02c8a1] (1:8506, c:35): unexpected 'ł'

Works perfectly fine with all other focus trees.

Thanks,

P.S. Cool code

**Comment by 22oroda** [comment] 2022-07-27 11:54
For anyone who is not good at coding the parathensis is where the error is, so here it means line 8506 character 35, unexpected is a character it doesn't recongnize so just get rid of that and to find the file just go to the console that comes with the code and find the last file it was on then locate the character.

Just figured this one out...

**Comment by malashin** [comment] 2022-07-27 21:38
Hi @22oroda 

The issue is fixed in https://github.com/malashin/hoi4treesnap/releases/tag/v0.5.10
Added extended latin and cyrillic unicode letters to the parser. 'ł' is a one of those.

Thank you for the report.

**Closed as completed by malashin** 2022-07-27 21:38 UTC
